baseurl = "http://localhost:1313/" # 设置域名，生产环境有效
title = "融禾科技"
languageCode = "zh"
defaultContentLanguage = "zh"
theme = 'hugo-universal-theme'


# Hugo Markdown 配置，https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup.goldmark.renderer]
    unsafe = false # 允许 markdown 中使用 html，默认为 false
      