# 网站的根URL
baseurl = "https://devcows.github.io/hugo-universal-theme/" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
# 首页的标题
title = "Universal"
# 设置使用的主题
theme = "hugo-universal-theme"
themesDir = "../.."
# 设置网站默认的语言，所有的语言翻译文件在i18n目录下，文件名于此处配置的语言代码相同
languageCode = "zh"
defaultContentLanguage = "zh"
# 值为空的话则不启用disqus，因为需要翻墙才能访问，所以我们不启用
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false


# 板块化分
# 权重对应在页面上显示的次序

[menu]
[[menu.main]]
    name       = "主页"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "产品"
    identifier = "menu.products"
    url        = "/img/products/001.jpg"
    weight     = 2

[[menu.main]]
    name       = "工控机"
    identifier = "section.ipc"
    url        = "/"
    weight     = 1
    parent     = "menu.products"
    post       = 1

[[menu.main]]
    name       = "美联迷你工控机"
    url        = "/product/ml-mini-ops/"
    weight     = 1
    parent     = "section.ipc"

[[menu.main]]
    name       = "美联壁挂式工控机"
    url        = "/"
    weight     = 2
    parent     = "section.ipc"

[[menu.main]]
    name       = "美联4U工控机"
    url        = "/"
    weight     = 3
    parent     = "section.ipc"

[[menu.main]]    
    name       = "服务器"
    identifier = "section.server"
    url        = "/"
    weight     = 2
    parent     = "menu.products"
    post       = 1

[[menu.main]]
    name       = "美联服务器"
    url        = "/"
    weight     = 1
    parent     = "section.server"

[[menu.main]]
    name       = "触控一体机"
    identifier = "section.onetouch"
    url        = "/"
    weight     = 2
    parent     = "menu.products"
    post       = 2

[[menu.main]]
    name       = "立式自助终端查询一体机"
    url        = "/"
    weight     = 1
    parent     = "section.onetouch"

[[menu.main]]
    name       = "立式触摸查询一体机"
    url        = "/"
    weight     = 2
    parent     = "section.onetouch"

[[menu.main]]
    name       = "卧式触摸一体机"
    url        = "/"
    weight     = 3
    parent     = "section.onetouch"

[[menu.main]]
    name       = "壁挂触摸查询一体机"
    url        = "/"
    weight     = 4
    parent     = "section.onetouch"

[[menu.main]]
    name       = "嵌入式触摸一体机"
    url        = "/"
    weight     = 5
    parent     = "section.onetouch"

[[menu.main]]
    name       = "会议/教学 触摸一体机"
    url        = "/"
    weight     = 6
    parent     = "section.onetouch"

[[menu.main]]
    name       = "解决方案"
    identifier = "menu.solution"
    url        = "/sulotion/"
    weight     = 3

[[menu.main]]
    name       = "合作伙伴"
    identifier = "menu.partner"
    weight     = 4

[[menu.main]]
    name       = "部分长期合作单位"
    identifier = "section.partner.longterm"
    url        = "/"
    weight     = 1
    parent     = "menu.partner"
    post       = 1

[[menu.main]]
    name       = "上海科大智能（上市公司）"
    url        = "/"
    weight     = 1
    parent     = "section.partner.longterm"

[[menu.main]]
    name       = "合肥永乾智能控制技术有限公司"
    url        = "/"
    weight     = 2
    parent     = "section.partner.longterm"

[[menu.main]]
    name       = "昆山动爵健身"
    url        = "/"
    weight     = 3
    parent     = "section.partner.longterm"

[[menu.main]]
    name       = "连云港卫生管理局"
    url        = "/"
    weight     = 4
    parent     = "section.partner.longterm"    

[[menu.main]]
    name       = "响水县教育局"
    url        = "/"
    weight     = 5
    parent     = "section.partner.longterm"

[[menu.main]]
    name       = "部分施工项目"
    identifier = "section.partner.construction"
    url        = "/"
    weight     = 2
    parent     = "menu.partner"
    post       = 2

[[menu.main]]
    name       = "福建巨电新能源股份有限公司弱电施工"
    url        = "/"
    weight     = 1
    parent     = "section.partner.construction"

[[menu.main]]
    name       = "无锡上汽大通弱电施工"
    url        = "/"
    weight     = 2
    parent     = "section.partner.construction"

[[menu.main]]
    name       = "镇江力信网络整改弱电施工"
    url        = "/"
    weight     = 3
    parent     = "section.partner.construction"

[[menu.main]]
    name       = "河北唐山国轩电池厂弱电施工"
    url        = "/"
    weight     = 4
    parent     = "section.partner.construction"

[[menu.main]]
    name       = "福建武夷山巨电监控设备安装"
    url        = "/"
    weight     = 5
    parent     = "section.partner.construction"

[[menu.main]]
    name       = "江西上饶瑞华网络布线施工"
    url        = "/"
    weight     = 6
    parent     = "section.partner.construction"

[[menu.main]]
    name       = "江西少绕星盈弱电施工项目"
    url        = "/"
    weight     = 7
    parent     = "section.partner.construction"                    

[[menu.main]]
    name       = "常州太平洋"
    url        = "/"
    weight     = 8
    parent     = "section.partner.construction"

[[menu.main]]
    name       = "嘉兴平湖安悦"
    url        = "/"
    weight     = 9
    parent     = "section.partner.construction"    

[[menu.main]]
    name       = "技术支持"
    identifier = "menu.techsupport"
    url        = "/tech/"
    weight     = 5

[[menu.main]]
    name       = "关于融禾"
    identifier = "menu.about"
    url        = "/about/"
    weight     = 6

[[menu.main]]
    name       = "联系我们"
    identifier = "menu.contact"
    url        = "/contact/"
    weight     = 7


# 顶栏，可选择显示
[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:hello@universal.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"


# 配置参数，HTML中可以引用
[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    # 文章默认的SEO设置
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["blog", "product"] # 查询的目录
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    #enableGoogleMaps = true
    #googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    #latitude = "-12.043333"
    #longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = """<p>全系列触控商显整机生产厂家
    <br>产品全 | 款式新 | 技术强 | 质量优 | 服务款
    <br> 全球首推-以换代修, 30天无理由承诺
    </p>"""
    copyright = "Copyright © 2018 - 2023 昆山融禾电子科技有限公司 版权所有"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "RHMEILIAN"

    logo = "img/logo.jpg"
    logo_small = "img/logo.jpg"
    contact_url = "/contact"
    address = """<p class="text-uppercase">
        <strong>Tel : 0512-55556666</strong>
        <br>昆山市前进东路台协国际商务广场1010室
      </p>
      """

[permalinks]
    # 博客中文章的URL规则，可以为/blog/2018/05/24/mypost/
    blog = "/blog/:year/:month/:day/:filename/"

# 是否启用顶层通知栏
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">昆山融禾电子科技有限公司</p>
      <p class="hidden-md hidden-lg">
      <a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# 是否启用右侧的小工具
[params.widgets]
    categories = true
    tags = false
    search = false

# Carousel轮播
# 轮播内容位于 data/carousel 中
[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.goods]
    enable = true
    cols = 4
    title = "我们的产品"
    subtitle = ""

[params.features]
    enable = false
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "我们的合作伙伴"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
